package errs

const WRONG_ARGS = "Wrong args"
const DIAL_ERR = "Errors while trying to connect"
const CONV_ERR = "Errors while converting from int to str"
const INVALID_PORT = "Port not valid"
const PORT_OCCUPIED = "Errors while trying to listen, port may be occupied"
const ACCEPT_ERR = "Errors while trying to accept the connection"
const PUB_KEY_ERR = "Errors while trying to receive public key"
const SEQ_NUM_TOO_LARGE = "received sequence number, but the difference with ours is too large, dropping"
const SEQ_NUM_NOT_FOUND_CACHE = "expected seq number is bigger than the received one, and a corrisponding key was not found in cache"
const WTF_ERR = "how did we get here"
const B64_ERR = "\rerrors while trying to decode base64"
const DEC_ERR = "\rerrors while trying to decrypt"
const CONN_ENDED = "\nconnection ended :p"
const READ_ERR = "errors while reading"
const IPV4_ERR = "IPv4 not valid"
const IPv6_ERR = "IPv6 not valid"
const GEN_IP_ERR = "IP is not IPv4 or IPv6"
